In [6]:
import pandas as pd

In [7]:
data = {
    "Customer_Name": ["John Doe", "Alice Smith", "Bob Johnson"],
    "Order_ID": ["ORD-12345", "ORD-67890", "ORD-54321"],
    "Date": ["2026-04-14", "2026-05-20", "2026-06-10"]
}

df = pd.DataFrame(data)

In [8]:
df

  Customer_Name   Order_ID        Date
0      John Doe  ORD-12345  2026-04-14
1   Alice Smith  ORD-67890  2026-05-20
2   Bob Johnson  ORD-54321  2026-06-10

In [9]:
# Customer_Name  convert to First_name And Last_Name two Diffrent Column
df[["First_Name", "Last_Name"]] = df["Customer_Name"].str.split(" ", expand=True)

In [10]:
df

  Customer_Name   Order_ID        Date First_Name Last_Name
0      John Doe  ORD-12345  2026-04-14       John       Doe
1   Alice Smith  ORD-67890  2026-05-20      Alice     Smith
2   Bob Johnson  ORD-54321  2026-06-10        Bob   Johnson

In [11]:
# Order_ID  convert to Order_Type and Order_Number two Diffrent Column
df[["Order_Type", "Order_Number"]] = df["Order_ID"].str.split("-", expand=True)

In [12]:
df

,Customer_Name,Order_ID,Date,First_Name,Last_Name,Order_Type,Order_Number
0,John Doe,ORD-12345,2026-04-14,John,Doe,ORD,12345
1,Alice Smith,ORD-67890,2026-05-20,Alice,Smith,ORD,67890
2,Bob Johnson,ORD-54321,2026-06-10,Bob,Johnson,ORD,54321

In [13]:

# Date convert to Year,Month,Day three Diffrent Column
df["Date"] = pd.to_datetime(df["Date"])

df["Year"] = df["Date"].dt.year
df["Month"] = df["Date"].dt.month
df["Day"] = df["Date"].dt.day

In [14]:
df

,Customer_Name,Order_ID,Date,First_Name,Last_Name,Order_Type,Order_Number,Year,Month,Day
0,John Doe,ORD-12345,2026-04-14,John,Doe,ORD,12345,2026,4,14
1,Alice Smith,ORD-67890,2026-05-20,Alice,Smith,ORD,67890,2026,5,20
2,Bob Johnson,ORD-54321,2026-06-10,Bob,Johnson,ORD,54321,2026,6,10

In [15]:
#Drop Existing Column After Splitting
df.drop(columns=["Customer_Name", "Order_ID", "Date"], inplace=True)

In [16]:
df

  First_Name Last_Name Order_Type Order_Number  Year  Month  Day
0       John       Doe        ORD        12345  2026      4   14
1      Alice     Smith        ORD        67890  2026      5   20
2        Bob   Johnson        ORD        54321  2026      6   10