In [19]:
import pandas as pd

In [20]:
data = {
    "Name": ["A", "B", "C"],
    "Age": [25, 40, 30],
    "Salary": [50000, 80000, 60000],
    "Join_Date": ["2020-01-15", "2018-07-10", "2021-03-20"]
}

df = pd.DataFrame(data)

In [21]:
df

  Name  Age  Salary   Join_Date
0    A   25   50000  2020-01-15
1    B   40   80000  2018-07-10
2    C   30   60000  2021-03-20

In [9]:
#Salary_per_Age New Column Create

df["Salary_per_Age"] = df["Salary"] / df["Age"]

In [10]:
df

  Name  Age  Salary   Join_Date  Salary_per_Age
0    A   25   50000  2020-01-15          2000.0
1    B   40   80000  2018-07-10          2000.0
2    C   30   60000  2021-03-20          2000.0

In [11]:
#Join_Date object to datetime convert
df["Join_Date"] = pd.to_datetime(df["Join_Date"])

#Join_Year New Column Create
df["Join_Year"] = df["Join_Date"].dt.year

#Join_Month New Column Create
df["Join_Month"] = df["Join_Date"].dt.month

In [12]:
df

  Name  Age  Salary  Join_Date  Salary_per_Age  Join_Year  Join_Month
0    A   25   50000 2020-01-15          2000.0       2020           1
1    B   40   80000 2018-07-10          2000.0       2018           7
2    C   30   60000 2021-03-20          2000.0       2021           3

In [13]:
#Age_Group New Column Create and convert to group
df["Age_Group"] = pd.cut(df["Age"],
                        bins=[0, 30, 50],
                        labels=["Young", "Adult"])

In [14]:
df

,Name,Age,Salary,Join_Date,Salary_per_Age,Join_Year,Join_Month,Age_Group
0,A,25,50000,2020-01-15,2000.0,2020,1,Young
1,B,40,80000,2018-07-10,2000.0,2018,7,Adult
2,C,30,60000,2021-03-20,2000.0,2021,3,Young

In [15]:
#Age_Salary New Column Create multiplication of Age and Salary
df["Age_Salary"] = df["Age"] * df["Salary"]

In [16]:
df

,Name,Age,Salary,Join_Date,Salary_per_Age,Join_Year,Join_Month,Age_Group,Age_Salary
0,A,25,50000,2020-01-15,2000.0,2020,1,Young,1250000
1,B,40,80000,2018-07-10,2000.0,2018,7,Adult,3200000
2,C,30,60000,2021-03-20,2000.0,2021,3,Young,1800000

In [17]:
#High_Salary New Column Create salary greater than 60000 give boolean value
df["High_Salary"] = df["Salary"] > 60000

In [18]:
df

,Name,Age,Salary,Join_Date,Salary_per_Age,Join_Year,Join_Month,Age_Group,Age_Salary,High_Salary
0,A,25,50000,2020-01-15,2000.0,2020,1,Young,1250000,False
1,B,40,80000,2018-07-10,2000.0,2018,7,Adult,3200000,True
2,C,30,60000,2021-03-20,2000.0,2021,3,Young,1800000,False