In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv('/home/database.csv',usecols=['Date'])
df1 = pd.read_csv('/home/database.csv',usecols=['Time'])

In [ ]:
df

,Date,year,month,day,monthname,dayofweek,dayname,Isweekend,week,quarter,semester
0,1965-01-02,1965.0,1.0,2.0,January,5.0,Saturday,Yes,53,1.0,1
1,1965-01-04,1965.0,1.0,4.0,January,0.0,Monday,No,1,1.0,1
2,1965-01-05,1965.0,1.0,5.0,January,1.0,Tuesday,No,1,1.0,1
3,1965-01-08,1965.0,1.0,8.0,January,4.0,Friday,No,1,1.0,1
4,1965-01-09,1965.0,1.0,9.0,January,5.0,Saturday,Yes,1,1.0,1
...,...,...,...,...,...,...,...,...,...,...,...
23407,NaT,NaN,NaN,NaN,NaN,NaN,NaN,No,<NA>,NaN,2
23408,NaT,NaN,NaN,NaN,NaN,NaN,NaN,No,<NA>,NaN,2
23409,NaT,NaN,NaN,NaN,NaN,NaN,NaN,No,<NA>,NaN,2
23410,NaT,NaN,NaN,NaN,NaN,NaN,NaN,No,<NA>,NaN,2
23411,NaT,NaN,NaN,NaN,NaN,NaN,NaN,No,<NA>,NaN,2

In [ ]:
df.head()

,Date,year,month,day,monthname,dayofweek,dayname,Isweekend,week,quarter,semester
0,1965-01-02,1965.0,1.0,2.0,January,5.0,Saturday,Yes,53,1.0,1
1,1965-01-04,1965.0,1.0,4.0,January,0.0,Monday,No,1,1.0,1
2,1965-01-05,1965.0,1.0,5.0,January,1.0,Tuesday,No,1,1.0,1
3,1965-01-08,1965.0,1.0,8.0,January,4.0,Friday,No,1,1.0,1
4,1965-01-09,1965.0,1.0,9.0,January,5.0,Saturday,Yes,1,1.0,1

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23412 entries, 0 to 23411
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    3378 non-null   datetime64[ns]
 1   year    3378 non-null   float64
dtypes: datetime64[ns](1), float64(1)
memory usage: 365.9 KB

In [ ]:
df.isnull().sum()

Date    20034
year    20034
dtype: int64

           Date    year
0    1965-01-02  1965.0
1    1965-01-04  1965.0
2    1965-01-05  1965.0
3    1965-01-08  1965.0
4    1965-01-09  1965.0
...         ...     ...
3373 1975-02-17  1975.0
3374 1975-02-20  1975.0
3375 1975-02-22  1975.0
3376 1975-02-22  1975.0
3377 1975-02-22  1975.0

[3378 rows x 2 columns]

In [ ]:
df['Date'] = pd.to_datetime(df['Date'], format='mixed', errors='coerce')

In [ ]:
df

            Date    year
0     1965-01-02  1965.0
1     1965-01-04  1965.0
2     1965-01-05  1965.0
3     1965-01-08  1965.0
4     1965-01-09  1965.0
...          ...     ...
23407        NaT     NaN
23408        NaT     NaN
23409        NaT     NaN
23410        NaT     NaN
23411        NaT     NaN

[23412 rows x 2 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23412 entries, 0 to 23411
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    3378 non-null   datetime64[ns]
 1   year    3378 non-null   float64
dtypes: datetime64[ns](1), float64(1)
memory usage: 365.9 KB

In [ ]:
df.dropna()

           Date    year
0    1965-01-02  1965.0
1    1965-01-04  1965.0
2    1965-01-05  1965.0
3    1965-01-08  1965.0
4    1965-01-09  1965.0
...         ...     ...
3373 1975-02-17  1975.0
3374 1975-02-20  1975.0
3375 1975-02-22  1975.0
3376 1975-02-22  1975.0
3377 1975-02-22  1975.0

[3378 rows x 2 columns]

In [ ]:
df['year'] = df['Date'].dt.year

df.head()

,Date,year,month,day,monthname,dayofweek,dayname,Isweekend,week,quarter,semester
0,1965-01-02,1965.0,1.0,2.0,January,5.0,Saturday,Yes,53,1.0,1
1,1965-01-04,1965.0,1.0,4.0,January,0.0,Monday,No,1,1.0,1
2,1965-01-05,1965.0,1.0,5.0,January,1.0,Tuesday,No,1,1.0,1
3,1965-01-08,1965.0,1.0,8.0,January,4.0,Friday,No,1,1.0,1
4,1965-01-09,1965.0,1.0,9.0,January,5.0,Saturday,Yes,1,1.0,1

In [ ]:
df['month'] = df['Date'].dt.month

df.head()

        Date    year  month
0 1965-01-02  1965.0    1.0
1 1965-01-04  1965.0    1.0
2 1965-01-05  1965.0    1.0
3 1965-01-08  1965.0    1.0
4 1965-01-09  1965.0    1.0

In [ ]:
df['day'] = df['Date'].dt.day

df.head()

        Date    year  month  day
0 1965-01-02  1965.0    1.0  2.0
1 1965-01-04  1965.0    1.0  4.0
2 1965-01-05  1965.0    1.0  5.0
3 1965-01-08  1965.0    1.0  8.0
4 1965-01-09  1965.0    1.0  9.0

In [ ]:
df['monthname'] = df['Date'].dt.month_name()

df.head()

        Date    year  month  day monthname
0 1965-01-02  1965.0    1.0  2.0   January
1 1965-01-04  1965.0    1.0  4.0   January
2 1965-01-05  1965.0    1.0  5.0   January
3 1965-01-08  1965.0    1.0  8.0   January
4 1965-01-09  1965.0    1.0  9.0   January

In [ ]:
df['dayofweek'] = df['Date'].dt.dayofweek

df.head()

        Date    year  month  day monthname  dayofweek
0 1965-01-02  1965.0    1.0  2.0   January        5.0
1 1965-01-04  1965.0    1.0  4.0   January        0.0
2 1965-01-05  1965.0    1.0  5.0   January        1.0
3 1965-01-08  1965.0    1.0  8.0   January        4.0
4 1965-01-09  1965.0    1.0  9.0   January        5.0

In [ ]:
df['dayname'] = df['Date'].dt.day_name()
df.head()

        Date    year  month  day monthname  dayofweek   dayname
0 1965-01-02  1965.0    1.0  2.0   January        5.0  Saturday
1 1965-01-04  1965.0    1.0  4.0   January        0.0    Monday
2 1965-01-05  1965.0    1.0  5.0   January        1.0   Tuesday
3 1965-01-08  1965.0    1.0  8.0   January        4.0    Friday
4 1965-01-09  1965.0    1.0  9.0   January        5.0  Saturday

In [ ]:
df['Isweekend'] = np.where(df['dayname'].isin(['Sunday', 'Saturday']), 'Yes','No')
df.head()

        Date    year  month  day monthname  dayofweek   dayname Isweekend
0 1965-01-02  1965.0    1.0  2.0   January        5.0  Saturday       Yes
1 1965-01-04  1965.0    1.0  4.0   January        0.0    Monday        No
2 1965-01-05  1965.0    1.0  5.0   January        1.0   Tuesday        No
3 1965-01-08  1965.0    1.0  8.0   January        4.0    Friday        No
4 1965-01-09  1965.0    1.0  9.0   January        5.0  Saturday       Yes

In [ ]:
df['week'] = df['Date'].dt.isocalendar().week
df.head()

,Date,year,month,day,monthname,dayofweek,dayname,Isweekend,week
0,1965-01-02,1965.0,1.0,2.0,January,5.0,Saturday,Yes,53
1,1965-01-04,1965.0,1.0,4.0,January,0.0,Monday,No,1
2,1965-01-05,1965.0,1.0,5.0,January,1.0,Tuesday,No,1
3,1965-01-08,1965.0,1.0,8.0,January,4.0,Friday,No,1
4,1965-01-09,1965.0,1.0,9.0,January,5.0,Saturday,Yes,1

In [ ]:
df['quarter'] = df['Date'].dt.quarter
df.head()

,Date,year,month,day,monthname,dayofweek,dayname,Isweekend,week,quarter
0,1965-01-02,1965.0,1.0,2.0,January,5.0,Saturday,Yes,53,1.0
1,1965-01-04,1965.0,1.0,4.0,January,0.0,Monday,No,1,1.0
2,1965-01-05,1965.0,1.0,5.0,January,1.0,Tuesday,No,1,1.0
3,1965-01-08,1965.0,1.0,8.0,January,4.0,Friday,No,1,1.0
4,1965-01-09,1965.0,1.0,9.0,January,5.0,Saturday,Yes,1,1.0

In [ ]:
df['semester'] = np.where(df['quarter'].isin([1,2]), 1, 2)
df.head()

,Date,year,month,day,monthname,dayofweek,dayname,Isweekend,week,quarter,semester
0,1965-01-02,1965.0,1.0,2.0,January,5.0,Saturday,Yes,53,1.0,1
1,1965-01-04,1965.0,1.0,4.0,January,0.0,Monday,No,1,1.0,1
2,1965-01-05,1965.0,1.0,5.0,January,1.0,Tuesday,No,1,1.0,1
3,1965-01-08,1965.0,1.0,8.0,January,4.0,Friday,No,1,1.0,1
4,1965-01-09,1965.0,1.0,9.0,January,5.0,Saturday,Yes,1,1.0,1

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23412 entries, 0 to 23411
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Time    23412 non-null  object
dtypes: object(1)
memory usage: 183.0+ KB

In [ ]:
df1['time'] = pd.to_datetime(df1['Time'], errors='coerce', utc=True)

/tmp/ipykernel_9835/1807530476.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df1['time'] = pd.to_datetime(df1['Time'], errors='coerce', utc=True)

In [ ]:
df1

           Time                      time
0      13:44:18 2026-04-11 13:44:18+00:00
1      11:29:49 2026-04-11 11:29:49+00:00
2      18:05:58 2026-04-11 18:05:58+00:00
3      18:49:43 2026-04-11 18:49:43+00:00
4      13:32:50 2026-04-11 13:32:50+00:00
...         ...                       ...
23407  08:22:12 2026-04-11 08:22:12+00:00
23408  09:13:47 2026-04-11 09:13:47+00:00
23409  12:38:51 2026-04-11 12:38:51+00:00
23410  22:30:19 2026-04-11 22:30:19+00:00
23411  20:08:28 2026-04-11 20:08:28+00:00

[23412 rows x 2 columns]

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23412 entries, 0 to 23411
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Time    23412 non-null  object
 1   time    23412 non-null  datetime64[ns, UTC]
dtypes: datetime64[ns, UTC](1), object(1)
memory usage: 365.9+ KB

In [ ]:
df1['hour'] = df1['time'].dt.hour
df1['min'] = df1['time'].dt.minute
df1['sec'] = df1['time'].dt.second

df1.head()

       Time                      time  hour  min  sec
0  13:44:18 2026-04-11 13:44:18+00:00    13   44   18
1  11:29:49 2026-04-11 11:29:49+00:00    11   29   49
2  18:05:58 2026-04-11 18:05:58+00:00    18    5   58
3  18:49:43 2026-04-11 18:49:43+00:00    18   49   43
4  13:32:50 2026-04-11 13:32:50+00:00    13   32   50

In [ ]:
df1['times'] = df1['time'].dt.time

df1.head()

       Time                      time  hour  min  sec     times
0  13:44:18 2026-04-11 13:44:18+00:00    13   44   18  13:44:18
1  11:29:49 2026-04-11 11:29:49+00:00    11   29   49  11:29:49
2  18:05:58 2026-04-11 18:05:58+00:00    18    5   58  18:05:58
3  18:49:43 2026-04-11 18:49:43+00:00    18   49   43  18:49:43
4  13:32:50 2026-04-11 13:32:50+00:00    13   32   50  13:32:50