In [1]:
import numpy as np
import pandas as pd

In [3]:

df = pd.read_csv('/home/insurance.csv')

In [4]:
df

      age     sex   bmi  children smoker     region  expenses
0      19  female  27.9         0    yes  southwest  16884.92
1      18    male  33.8         1     no  southeast   1725.55
2      28    male  33.0         3     no  southeast   4449.46
3      33    male  22.7         0     no  northwest  21984.47
4      32    male  28.9         0     no  northwest   3866.86
...   ...     ...   ...       ...    ...        ...       ...
1333   50    male  31.0         3     no  northwest  10600.55
1334   18  female  31.9         0     no  northeast   2205.98
1335   18  female  36.9         0     no  southeast   1629.83
1336   21  female  25.8         0     no  southwest   2007.95
1337   61  female  29.1         0    yes  northwest  29141.36

[1338 rows x 7 columns]

In [5]:
df.drop(['age', 'bmi','children','expenses'], axis=1, inplace=True)

In [6]:
df

         sex smoker     region
0     female    yes  southwest
1       male     no  southeast
2       male     no  southeast
3       male     no  northwest
4       male     no  northwest
...      ...    ...        ...
1333    male     no  northwest
1334  female     no  northeast
1335  female     no  southeast
1336  female     no  southwest
1337  female    yes  northwest

[1338 rows x 3 columns]

In [7]:
df['sex'].value_counts()

sex
male      676
female    662
Name: count, dtype: int64

In [8]:
df['smoker'].value_counts()

smoker
no     1064
yes     274
Name: count, dtype: int64

In [12]:
df['region'].value_counts()

region
southeast    364
southwest    325
northwest    325
northeast    324
Name: count, dtype: int64

In [14]:
pd.get_dummies(df,columns=['sex','region'])

,smoker,sex_female,sex_male,region_northeast,region_northwest,region_southeast,region_southwest
0,yes,True,False,False,False,False,True
1,no,False,True,False,False,True,False
2,no,False,True,False,False,True,False
3,no,False,True,False,True,False,False
4,no,False,True,False,True,False,False
...,...,...,...,...,...,...,...
1333,no,False,True,False,True,False,False
1334,no,True,False,True,False,False,False
1335,no,True,False,False,False,True,False
1336,no,True,False,False,False,False,True
1337,yes,True,False,False,True,False,False

In [15]:
from sklearn.model_selection import train_test_split

X = df[['sex', 'region']]
y = df['smoker']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=2
)

In [16]:
from sklearn.preprocessing import OneHotEncoder

In [17]:
import numpy as np

ohe = OneHotEncoder(sparse_output=False, dtype=np.int32)

In [18]:
ohe.fit(X_train[['sex', 'region']])

OneHotEncoder(dtype=<class 'numpy.int32'>, sparse_output=False)

In [19]:
X_train_new = ohe.transform(X_train[['sex', 'region']])
X_test_new = ohe.transform(X_test[['sex', 'region']])

In [20]:
X_train_new

array([[1, 0, 1, 0, 0, 0],
       [0, 1, 0, 1, 0, 0],
       [1, 0, 0, 0, 0, 1],
       ...,
       [0, 1, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 1, 0, 0, 0]], dtype=int32)

In [21]:
X_test_new

array([[0, 1, 1, 0, 0, 0],
       [1, 0, 1, 0, 0, 0],
       [0, 1, 1, 0, 0, 0],
       ...,
       [1, 0, 0, 1, 0, 0],
       [0, 1, 0, 0, 1, 0],
       [0, 1, 0, 1, 0, 0]], dtype=int32)