In [ ]:
import numpy as np
import pandas as pd

In [ ]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [ ]:
df = pd.read_csv('/home/insurance.csv')

In [ ]:
df

      age     sex   bmi  children smoker     region  expenses
0      19  female  27.9         0    yes  southwest  16884.92
1      18    male  33.8         1     no  southeast   1725.55
2      28    male  33.0         3     no  southeast   4449.46
3      33    male  22.7         0     no  northwest  21984.47
4      32    male  28.9         0     no  northwest   3866.86
...   ...     ...   ...       ...    ...        ...       ...
1333   50    male  31.0         3     no  northwest  10600.55
1334   18  female  31.9         0     no  northeast   2205.98
1335   18  female  36.9         0     no  southeast   1629.83
1336   21  female  25.8         0     no  southwest   2007.95
1337   61  female  29.1         0    yes  northwest  29141.36

[1338 rows x 7 columns]

In [ ]:
df.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
expenses    0
dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['expenses']),df['expenses'],
                                                test_size=0.2)

In [ ]:
X_train

      age     sex   bmi  children smoker     region
70     27  female  24.8         0    yes  southeast
1291   19    male  34.9         0    yes  southwest
553    52  female  31.7         2     no  northwest
599    52  female  37.5         2     no  northwest
765    57  female  31.8         0     no  northwest
...   ...     ...   ...       ...    ...        ...
768    64  female  39.7         0     no  southwest
885    32    male  28.9         1    yes  southeast
450    39    male  29.6         4     no  southwest
898    18  female  40.3         0     no  southeast
1162   30    male  38.8         1     no  southeast

[1070 rows x 6 columns]

In [ ]:
y_train

70      16577.78
1291    34828.65
553     11187.66
599     33471.97
765     11842.62
          ...
768     14319.03
885     19719.69
450      7512.27
898      1634.57
1162    18963.17
Name: expenses, Length: 1070, dtype: float64

In [ ]:
df['sex'].value_counts()

sex
male      676
female    662
Name: count, dtype: int64

In [ ]:
df['smoker'].value_counts()

smoker
no     1064
yes     274
Name: count, dtype: int64

In [ ]:
df['region'].value_counts()

region
southeast    364
southwest    325
northwest    325
northeast    324
Name: count, dtype: int64

In [ ]:
X_train_age= X_train['age']

In [ ]:
X_train_age

70      27
1291    19
553     52
599     52
765     57
        ..
768     64
885     32
450     39
898     18
1162    30
Name: age, Length: 1070, dtype: int64

In [ ]:
X_test_age= X_test['age']

In [ ]:
X_test_age

1156    19
78      22
234     39
295     18
912     59
        ..
820     45
1084    62
977     26
389     24
1210    36
Name: age, Length: 268, dtype: int64

In [ ]:
X_train_bmi= X_train['bmi']

In [ ]:
X_train_bmi

70      24.8
1291    34.9
553     31.7
599     37.5
765     31.8
        ...
768     39.7
885     28.9
450     29.6
898     40.3
1162    38.8
Name: bmi, Length: 1070, dtype: float64

In [ ]:
X_test_bmi= X_test['bmi']

In [ ]:
X_test_bmi

1156    44.9
78      39.8
234     24.5
295     23.0
912     26.7
        ...
820     33.7
1084    30.5
977     29.2
389     30.2
1210    30.9
Name: bmi, Length: 268, dtype: float64

In [ ]:
X_train_children= X_train['children']

In [ ]:
X_train_children

70      0
1291    0
553     2
599     2
765     0
       ..
768     0
885     1
450     4
898     0
1162    1
Name: children, Length: 1070, dtype: int64

In [ ]:
X_test_children= X_test['children']

In [ ]:
X_test_children

1156    0
78      0
234     2
295     0
912     3
       ..
820     1
1084    2
977     1
389     3
1210    1
Name: children, Length: 268, dtype: int64

###1.Before Using Column Transformer

In [ ]:
# Ordinalencoding
oe = OrdinalEncoder(categories=[['no','yes']])
X_train_smoker = oe.fit_transform(X_train[['smoker']])
X_test_smoker = oe.fit_transform(X_test[['smoker']])
X_train_smoker.shape

(1070, 1)

In [ ]:
X_test_smoker.shape

(268, 1)

In [ ]:
# OneHotEncoding
ohe = OneHotEncoder(drop='first', sparse_output=False)
X_train_sex_region = ohe.fit_transform(X_train[['sex','region']])
X_test_sex_region = ohe.fit_transform(X_test[['sex','region']])
X_train_sex_region.shape

(1070, 4)

In [ ]:
X_test_sex_region.shape

(268, 4)

In [ ]:
X_train_transform = np.hstack((
    X_train[['age']],
    X_train[['bmi']],
    X_train_sex_region,
    X_train[['children']],
    X_train_smoker
))
X_test_transform = np.hstack((
    X_test[['age']],
    X_test[['bmi']],
    X_test_sex_region,
    X_test[['children']],
    X_test_smoker
))
X_train_transform.shape

(1070, 8)

####2.After using Column Transformer

In [ ]:
from sklearn.compose import ColumnTransformer

In [ ]:
colTransformer = ColumnTransformer(transformers=[
    ('col1',OrdinalEncoder(categories=[['no','yes']]),['smoker']),
    ('col2',OneHotEncoder(sparse_output=False,drop='first'),['sex','region'])
],remainder='passthrough')

In [ ]:
colTransformer.fit_transform(X_train).shape

(1070, 8)

In [ ]:
colTransformer.transform(X_test).shape

(268, 8)