In [ ]:
import pandas as pd

###1.Open CSV File

In [ ]:
df = pd.read_csv('/home/connecticut_real_estate_2026.csv')
df

,type,sub_type,text,listPrice,sqft,stories,beds,baths,baths_full,baths_full_calc,garage,year_built
0,single_family,NaN,One of the Best/Private Locations in this well...,217000,888.0,NaN,2.0,1.0,1.0,1.0,NaN,1969.0
1,single_family,NaN,ATTENTION INVESTORS and FLIPPERS!! BANK FORECL...,197600,2329.0,NaN,5.0,2.0,2.0,2.0,1.0,1927.0
2,multi_family,NaN,Investor Special - Value-Add Opportunity. Two-...,350000,1980.0,NaN,6.0,2.0,2.0,2.0,NaN,1900.0
3,single_family,NaN,Welcome home to this beautiful oversized Raise...,495000,2962.0,NaN,3.0,3.0,3.0,3.0,2.0,1986.0
4,single_family,NaN,OFFERS DUE ON MONDAY 3.16.2026 @ 3 pm. Charmin...,499000,2764.0,NaN,3.0,2.0,2.0,2.0,2.0,1992.0
...,...,...,...,...,...,...,...,...,...,...,...,...
8696,land,NaN,"expansive 7,841 sq. ft. parcel of residential ...",230000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8697,multi_family,NaN,Turnkey 3-family property in Waterbury's desir...,490000,2952.0,NaN,6.0,3.0,3.0,3.0,NaN,1915.0
8698,mobile,NaN,"2 Bedroom, 1 bath manufactured home. $110, 000...",110000,840.0,NaN,2.0,1.0,1.0,1.0,NaN,2003.0
8699,mobile,NaN,[Redacted Entity] is a 56 Foot long Manufactur...,150000,784.0,NaN,1.0,1.0,1.0,1.0,NaN,2005.0
8700,multi_family,NaN,"Welcome to [Redacted Entity], Bridgeport. An e...",780000,3940.0,NaN,10.0,4.0,4.0,4.0,NaN,2026.0

###2. Opening a csv file from an URL

In [ ]:

import requests
from io import StringIO

url = "https://raw.githubusercontent.com/Tutoriallearn/Pandas-For-Data-Science-and-AI-ML/main/orders.csv"

headers = {"User-Agent": "Mozilla/5.0"}
req = requests.get(url, headers=headers)

data = StringIO(req.text)

df = pd.read_csv(data)

print(df)

           date  product_id  city_id  orders
0    2019-12-10        5628       25       3
1    2018-08-15        3646       14     157
2    2018-10-23        1859       25       1
3    2019-08-17        7292       25       1
4    2019-01-06        4344       25       3
..          ...         ...      ...     ...
995  2018-10-08         255       13       1
996  2018-12-06        5521        7       1
997  2019-05-07         487       26      14
998  2019-03-03        1503       21       2
999  2019-10-15        6371        7      22

[1000 rows x 4 columns]

###3. Show Parameter

In [ ]:
pd.read_csv('/home/connecticut_real_estate_2026.csv',sep='\t',names=['type','text','listPrice','sqft','stories','beds'])

,type,text,listPrice,sqft,stories,beds
0,"type,sub_type,text,listPrice,sqft,stories,beds...",NaN,NaN,NaN,NaN,NaN
1,"single_family,,""One of the Best/Private Locati...",NaN,NaN,NaN,NaN,NaN
2,"single_family,,ATTENTION INVESTORS and FLIPPER...",NaN,NaN,NaN,NaN,NaN
3,"multi_family,,""Investor Special - Value-Add Op...",NaN,NaN,NaN,NaN,NaN
4,"single_family,,""Welcome home to this beautiful...",NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
8697,"land,,""expansive 7,841 sq. ft. parcel of resid...",NaN,NaN,NaN,NaN,NaN
8698,"multi_family,,""Turnkey 3-family property in Wa...",NaN,NaN,NaN,NaN,NaN
8699,"mobile,,""2 Bedroom, 1 bath manufactured home. ...",NaN,NaN,NaN,NaN,NaN
8700,"mobile,,""[Redacted Entity] is a 56 Foot long M...",NaN,NaN,NaN,NaN,NaN
8701,"multi_family,,""Welcome to [Redacted Entity], B...",NaN,NaN,NaN,NaN,NaN

###4. Header parameter

In [ ]:
pd.read_csv('/home/connecticut_real_estate_2026.csv',header=1)

,single_family,Unnamed: 1,"One of the Best/Private Locations in this well-kept New England Village Community. Very nice 2-bedroom house, 1 Bath, Sunroom, Eat-in Kitchen/Dining area, Living room, Roof 12 years old, Heat pump 2012, Water heater 2011 and Vinyl siding 2012. Kitchen, baths, floors in excellent shape. Central A/C 11 yrs old & a spacious private yard / with storage shed. Note: property bordered by private road on 2 sides and an adjacent lot on 3rd side which is part of Village Community ownership and cannot be built on, which makes this a very-very private residence. Allowed 1 Small pet.",217000,888.0,Unnamed: 5,2.0,1.0,1.0.1,1.0.2,Unnamed: 10,1969.0
0,single_family,NaN,ATTENTION INVESTORS and FLIPPERS!! BANK FORECL...,197600,2329.0,NaN,5.0,2.0,2.0,2.0,1.0,1927.0
1,multi_family,NaN,Investor Special - Value-Add Opportunity. Two-...,350000,1980.0,NaN,6.0,2.0,2.0,2.0,NaN,1900.0
2,single_family,NaN,Welcome home to this beautiful oversized Raise...,495000,2962.0,NaN,3.0,3.0,3.0,3.0,2.0,1986.0
3,single_family,NaN,OFFERS DUE ON MONDAY 3.16.2026 @ 3 pm. Charmin...,499000,2764.0,NaN,3.0,2.0,2.0,2.0,2.0,1992.0
4,single_family,NaN,A Picture-Perfect Custom Cape in Ivoryton. Wel...,695000,2218.0,NaN,3.0,3.0,2.0,2.0,2.0,2014.0
...,...,...,...,...,...,...,...,...,...,...,...,...
8695,land,NaN,"expansive 7,841 sq. ft. parcel of residential ...",230000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8696,multi_family,NaN,Turnkey 3-family property in Waterbury's desir...,490000,2952.0,NaN,6.0,3.0,3.0,3.0,NaN,1915.0
8697,mobile,NaN,"2 Bedroom, 1 bath manufactured home. $110, 000...",110000,840.0,NaN,2.0,1.0,1.0,1.0,NaN,2003.0
8698,mobile,NaN,[Redacted Entity] is a 56 Foot long Manufactur...,150000,784.0,NaN,1.0,1.0,1.0,1.0,NaN,2005.0
8699,multi_family,NaN,"Welcome to [Redacted Entity], Bridgeport. An e...",780000,3940.0,NaN,10.0,4.0,4.0,4.0,NaN,2026.0

####5. use_cols parameter

In [ ]:
pd.read_csv('/home/connecticut_real_estate_2026.csv',usecols=['type','text','listPrice','sqft'])

,type,text,listPrice,sqft
0,single_family,One of the Best/Private Locations in this well...,217000,888.0
1,single_family,ATTENTION INVESTORS and FLIPPERS!! BANK FORECL...,197600,2329.0
2,multi_family,Investor Special - Value-Add Opportunity. Two-...,350000,1980.0
3,single_family,Welcome home to this beautiful oversized Raise...,495000,2962.0
4,single_family,OFFERS DUE ON MONDAY 3.16.2026 @ 3 pm. Charmin...,499000,2764.0
...,...,...,...,...
8696,land,"expansive 7,841 sq. ft. parcel of residential ...",230000,NaN
8697,multi_family,Turnkey 3-family property in Waterbury's desir...,490000,2952.0
8698,mobile,"2 Bedroom, 1 bath manufactured home. $110, 000...",110000,840.0
8699,mobile,[Redacted Entity] is a 56 Foot long Manufactur...,150000,784.0
8700,multi_family,"Welcome to [Redacted Entity], Bridgeport. An e...",780000,3940.0

###6. Squeeze parameters

In [ ]:
pd.read_csv('/home/connecticut_real_estate_2026.csv', usecols=['type']).squeeze()

0       single_family
1       single_family
2        multi_family
3       single_family
4       single_family
            ...
8696             land
8697     multi_family
8698           mobile
8699           mobile
8700     multi_family
Name: type, Length: 8701, dtype: object

###7. Skiprows/nrows Parameter

In [ ]:
pd.read_csv('/home/connecticut_real_estate_2026.csv',nrows=200)

,type,sub_type,text,listPrice,sqft,stories,beds,baths,baths_full,baths_full_calc,garage,year_built
0,single_family,NaN,One of the Best/Private Locations in this well...,217000,888.0,NaN,2.0,1.0,1.0,1.0,NaN,1969.0
1,single_family,NaN,ATTENTION INVESTORS and FLIPPERS!! BANK FORECL...,197600,2329.0,NaN,5.0,2.0,2.0,2.0,1.0,1927.0
2,multi_family,NaN,Investor Special - Value-Add Opportunity. Two-...,350000,1980.0,NaN,6.0,2.0,2.0,2.0,NaN,1900.0
3,single_family,NaN,Welcome home to this beautiful oversized Raise...,495000,2962.0,NaN,3.0,3.0,3.0,3.0,2.0,1986.0
4,single_family,NaN,OFFERS DUE ON MONDAY 3.16.2026 @ 3 pm. Charmin...,499000,2764.0,NaN,3.0,2.0,2.0,2.0,2.0,1992.0
...,...,...,...,...,...,...,...,...,...,...,...,...
195,single_family,NaN,"3-bedroom, 1-bath home with attached garage lo...",235000,1084.0,NaN,3.0,1.0,1.0,1.0,1.0,1976.0
196,single_family,NaN,Bring your creativity! This well-kept 3-bedroo...,465500,1917.0,NaN,3.0,2.0,2.0,2.0,2.0,1960.0
197,single_family,NaN,Fenwood Beach Association! This beautifully re...,859000,2042.0,NaN,2.0,2.0,2.0,2.0,NaN,1953.0
198,multi_family,NaN,2 family home located on a nice half acre leve...,299900,1920.0,NaN,5.0,2.0,2.0,2.0,NaN,1920.0
199,single_family,NaN,This handsome New England saltbox is sited on ...,745000,2066.0,NaN,3.0,3.0,2.0,2.0,2.0,1965.0

###8. Encoding parameter

In [ ]:
pd.read_csv('/home/connecticut_real_estate_2026.csv',encoding='latin-1')

,type,sub_type,text,listPrice,sqft,stories,beds,baths,baths_full,baths_full_calc,garage,year_built
0,single_family,NaN,One of the Best/Private Locations in this well...,217000,888.0,NaN,2.0,1.0,1.0,1.0,NaN,1969.0
1,single_family,NaN,ATTENTION INVESTORS and FLIPPERS!! BANK FORECL...,197600,2329.0,NaN,5.0,2.0,2.0,2.0,1.0,1927.0
2,multi_family,NaN,Investor Special - Value-Add Opportunity. Two-...,350000,1980.0,NaN,6.0,2.0,2.0,2.0,NaN,1900.0
3,single_family,NaN,Welcome home to this beautiful oversized Raise...,495000,2962.0,NaN,3.0,3.0,3.0,3.0,2.0,1986.0
4,single_family,NaN,OFFERS DUE ON MONDAY 3.16.2026 @ 3 pm. Charmin...,499000,2764.0,NaN,3.0,2.0,2.0,2.0,2.0,1992.0
...,...,...,...,...,...,...,...,...,...,...,...,...
8696,land,NaN,"expansive 7,841 sq. ft. parcel of residential ...",230000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8697,multi_family,NaN,Turnkey 3-family property in Waterbury's desir...,490000,2952.0,NaN,6.0,3.0,3.0,3.0,NaN,1915.0
8698,mobile,NaN,"2 Bedroom, 1 bath manufactured home. $110, 000...",110000,840.0,NaN,2.0,1.0,1.0,1.0,NaN,2003.0
8699,mobile,NaN,[Redacted Entity] is a 56 Foot long Manufactur...,150000,784.0,NaN,1.0,1.0,1.0,1.0,NaN,2005.0
8700,multi_family,NaN,"Welcome to [Redacted Entity], Bridgeport. An e...",780000,3940.0,NaN,10.0,4.0,4.0,4.0,NaN,2026.0

###9. Skip bad lines

In [ ]:
df = pd.read_csv(
    '/home/connecticut_real_estate_2026.csv',
    sep=';',
    encoding='latin-1',
    on_bad_lines='skip'
)

print(df)

     type,sub_type,text,listPrice,sqft,stories,beds,baths,baths_full,baths_full_calc,garage,year_built
0     single_family,,"One of the Best/Private Locati...
1     single_family,,ATTENTION INVESTORS and FLIPPER...
2     multi_family,,"Investor Special - Value-Add Op...
3     single_family,,"Welcome home to this beautiful...
4     single_family,,"OFFERS DUE ON MONDAY 3.16.2026...
...                                                 ...
8292  land,,"expansive 7,841 sq. ft. parcel of resid...
8293  multi_family,,"Turnkey 3-family property in Wa...
8294  mobile,,"2 Bedroom, 1 bath manufactured home. ...
8295  mobile,,"[Redacted Entity] is a 56 Foot long M...
8296  multi_family,,"Welcome to [Redacted Entity], B...

[8297 rows x 1 columns]

###10. dtypes parameter

In [ ]:
df = pd.read_csv('/home/connecticut_real_estate_2026.csv', dtype={'baths': 'Int64'})

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8701 entries, 0 to 8700
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   type             8701 non-null   object
 1   sub_type         1748 non-null   object
 2   text             8695 non-null   object
 3   listPrice        8701 non-null   int64
 4   sqft             7851 non-null   float64
 5   stories          1771 non-null   float64
 6   beds             7843 non-null   float64
 7   baths            7800 non-null   Int64
 8   baths_full       7818 non-null   float64
 9   baths_full_calc  7818 non-null   float64
 10  garage           5063 non-null   float64
 11  year_built       7797 non-null   float64
dtypes: Int64(1), float64(7), int64(1), object(3)
memory usage: 824.3+ KB

###11. na_values parameter

In [ ]:
pd.read_csv('/home/connecticut_real_estate_2026.csv',na_values=['mobile',])

,type,sub_type,text,listPrice,sqft,stories,beds,baths,baths_full,baths_full_calc,garage,year_built
0,single_family,NaN,One of the Best/Private Locations in this well...,217000,888.0,NaN,2.0,1.0,1.0,1.0,NaN,1969.0
1,single_family,NaN,ATTENTION INVESTORS and FLIPPERS!! BANK FORECL...,197600,2329.0,NaN,5.0,2.0,2.0,2.0,1.0,1927.0
2,multi_family,NaN,Investor Special - Value-Add Opportunity. Two-...,350000,1980.0,NaN,6.0,2.0,2.0,2.0,NaN,1900.0
3,single_family,NaN,Welcome home to this beautiful oversized Raise...,495000,2962.0,NaN,3.0,3.0,3.0,3.0,2.0,1986.0
4,single_family,NaN,OFFERS DUE ON MONDAY 3.16.2026 @ 3 pm. Charmin...,499000,2764.0,NaN,3.0,2.0,2.0,2.0,2.0,1992.0
...,...,...,...,...,...,...,...,...,...,...,...,...
8696,land,NaN,"expansive 7,841 sq. ft. parcel of residential ...",230000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8697,multi_family,NaN,Turnkey 3-family property in Waterbury's desir...,490000,2952.0,NaN,6.0,3.0,3.0,3.0,NaN,1915.0
8698,NaN,NaN,"2 Bedroom, 1 bath manufactured home. $110, 000...",110000,840.0,NaN,2.0,1.0,1.0,1.0,NaN,2003.0
8699,NaN,NaN,[Redacted Entity] is a 56 Foot long Manufactur...,150000,784.0,NaN,1.0,1.0,1.0,1.0,NaN,2005.0
8700,multi_family,NaN,"Welcome to [Redacted Entity], Bridgeport. An e...",780000,3940.0,NaN,10.0,4.0,4.0,4.0,NaN,2026.0

###12. Loading a huge dataset in chunks

In [ ]:
dfs = pd.read_csv('/home/connecticut_real_estate_2026.csv',chunksize=5000)

In [ ]:
for chunks in dfs:
    print(chunks.shape)

(5000, 12)
(3701, 12)

###13.To Find Json File

In [ ]:
pd.read_json('/home/iris.json')

     sepalLength  sepalWidth  petalLength  petalWidth    species
0            5.1         3.5          1.4         0.2     setosa
1            4.9         3.0          1.4         0.2     setosa
2            4.7         3.2          1.3         0.2     setosa
3            4.6         3.1          1.5         0.2     setosa
4            5.0         3.6          1.4         0.2     setosa
..           ...         ...          ...         ...        ...
145          6.7         3.0          5.2         2.3  virginica
146          6.3         2.5          5.0         1.9  virginica
147          6.5         3.0          5.2         2.0  virginica
148          6.2         3.4          5.4         2.3  virginica
149          5.9         3.0          5.1         1.8  virginica

[150 rows x 5 columns]

###14.To find Json file from API

In [ ]:
url = "https://dummyjson.com/products"

headers = {"User-Agent": "Mozilla/5.0"}

response = requests.get(url, headers=headers)

data = response.json()

df = pd.DataFrame(data)

print(df)

                                             products  total  skip  limit
0   {'id': 1, 'title': 'Essence Mascara Lash Princ...    194     0     30
1   {'id': 2, 'title': 'Eyeshadow Palette with Mir...    194     0     30
2   {'id': 3, 'title': 'Powder Canister', 'descrip...    194     0     30
3   {'id': 4, 'title': 'Red Lipstick', 'descriptio...    194     0     30
4   {'id': 5, 'title': 'Red Nail Polish', 'descrip...    194     0     30
5   {'id': 6, 'title': 'Calvin Klein CK One', 'des...    194     0     30
6   {'id': 7, 'title': 'Chanel Coco Noir Eau De', ...    194     0     30
7   {'id': 8, 'title': 'Dior J'adore', 'descriptio...    194     0     30
8   {'id': 9, 'title': 'Dolce Shine Eau de', 'desc...    194     0     30
9   {'id': 10, 'title': 'Gucci Bloom Eau de', 'des...    194     0     30
10  {'id': 11, 'title': 'Annibale Colombo Bed', 'd...    194     0     30
11  {'id': 12, 'title': 'Annibale Colombo Sofa', '...    194     0     30
12  {'id': 13, 'title': 'Bedside Table African Che...    194     0     30
13  {'id': 14, 'title': 'Knoll Saarinen Executive ...    194     0     30
14  {'id': 15, 'title': 'Wooden Bathroom Sink With...    194     0     30
15  {'id': 16, 'title': 'Apple', 'description': 'F...    194     0     30
16  {'id': 17, 'title': 'Beef Steak', 'description...    194     0     30
17  {'id': 18, 'title': 'Cat Food', 'description':...    194     0     30
18  {'id': 19, 'title': 'Chicken Meat', 'descripti...    194     0     30
19  {'id': 20, 'title': 'Cooking Oil', 'descriptio...    194     0     30
20  {'id': 21, 'title': 'Cucumber', 'description':...    194     0     30
21  {'id': 22, 'title': 'Dog Food', 'description':...    194     0     30
22  {'id': 23, 'title': 'Eggs', 'description': 'Fr...    194     0     30
23  {'id': 24, 'title': 'Fish Steak', 'description...    194     0     30
24  {'id': 25, 'title': 'Green Bell Pepper', 'desc...    194     0     30
25  {'id': 26, 'title': 'Green Chili Pepper', 'des...    194     0     30
26  {'id': 27, 'title': 'Honey Jar', 'description'...    194     0     30
27  {'id': 28, 'title': 'Ice Cream', 'description'...    194     0     30
28  {'id': 29, 'title': 'Juice', 'description': 'R...    194     0     30
29  {'id': 30, 'title': 'Kiwi', 'description': 'Nu...    194     0     30

In [ ]:
!pip install mysql.connector

Requirement already satisfied: mysql.connector in /usr/local/lib/python3.12/dist-packages (2.2.9)

In [ ]:
import mysql.connector

In [ ]:
conn = mysql.connector.connect(
    host="192.168.31.43",
    user="root",
    password="",
    database="restaurant_orders",
    port=3306
)

In [ ]:
df = pd.read_sql_query("SELECT * FROM connecticut_real_estate_2026",conn)

###15.Data find from API

In [ ]:
response = requests.get('https://dummyjson.com/products')
temp_df = pd.DataFrame(response.json())[['products','total']]
temp_df

                                             products  total
0   {'id': 1, 'title': 'Essence Mascara Lash Princ...    194
1   {'id': 2, 'title': 'Eyeshadow Palette with Mir...    194
2   {'id': 3, 'title': 'Powder Canister', 'descrip...    194
3   {'id': 4, 'title': 'Red Lipstick', 'descriptio...    194
4   {'id': 5, 'title': 'Red Nail Polish', 'descrip...    194
5   {'id': 6, 'title': 'Calvin Klein CK One', 'des...    194
6   {'id': 7, 'title': 'Chanel Coco Noir Eau De', ...    194
7   {'id': 8, 'title': 'Dior J'adore', 'descriptio...    194
8   {'id': 9, 'title': 'Dolce Shine Eau de', 'desc...    194
9   {'id': 10, 'title': 'Gucci Bloom Eau de', 'des...    194
10  {'id': 11, 'title': 'Annibale Colombo Bed', 'd...    194
11  {'id': 12, 'title': 'Annibale Colombo Sofa', '...    194
12  {'id': 13, 'title': 'Bedside Table African Che...    194
13  {'id': 14, 'title': 'Knoll Saarinen Executive ...    194
14  {'id': 15, 'title': 'Wooden Bathroom Sink With...    194
15  {'id': 16, 'title': 'Apple', 'description': 'F...    194
16  {'id': 17, 'title': 'Beef Steak', 'description...    194
17  {'id': 18, 'title': 'Cat Food', 'description':...    194
18  {'id': 19, 'title': 'Chicken Meat', 'descripti...    194
19  {'id': 20, 'title': 'Cooking Oil', 'descriptio...    194
20  {'id': 21, 'title': 'Cucumber', 'description':...    194
21  {'id': 22, 'title': 'Dog Food', 'description':...    194
22  {'id': 23, 'title': 'Eggs', 'description': 'Fr...    194
23  {'id': 24, 'title': 'Fish Steak', 'description...    194
24  {'id': 25, 'title': 'Green Bell Pepper', 'desc...    194
25  {'id': 26, 'title': 'Green Chili Pepper', 'des...    194
26  {'id': 27, 'title': 'Honey Jar', 'description'...    194
27  {'id': 28, 'title': 'Ice Cream', 'description'...    194
28  {'id': 29, 'title': 'Juice', 'description': 'R...    194
29  {'id': 30, 'title': 'Kiwi', 'description': 'Nu...    194