In [28]:
import pandas as pd
import numpy as np

data = {
    "Marks": [10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 200, 300]
}

df = pd.DataFrame(data)

In [29]:
df

    Marks
0      10
1      20
2      30
3      40
4      50
5      60
6      70
7      80
8      90
9     100
10    200
11    300

In [30]:
df['Marks'].describe()

count     12.000000
mean      87.500000
std       83.462022
min       10.000000
25%       37.500000
50%       65.000000
75%       92.500000
max      300.000000
Name: Marks, dtype: float64

In [31]:
lower = df["Marks"].quantile(0.01)   # 1st percentile
upper = df["Marks"].quantile(0.99)   # 99th percentile

print("Lower Limit:", lower)
print("Upper Limit:", upper)

Lower Limit: 11.1
Upper Limit: 289.00000000000006

In [32]:
outliers = df[(df["Marks"] < lower) | (df["Marks"] > upper)]

In [34]:
outliers

    Marks
0      10
11    300

In [35]:
df_clean = df[(df["Marks"] >= lower) & (df["Marks"] <= upper)]

In [36]:
df_clean

    Marks
1      20
2      30
3      40
4      50
5      60
6      70
7      80
8      90
9     100
10    200

####Capling

In [21]:
# Sample data
data = {
    "Salary": [25000, 27000, 29000, 31000, 33000, 35000,
               37000, 39000, 41000, 1000000]  # Outlier
}

df1 = pd.DataFrame(data)
print(df1)

    Salary
0    25000
1    27000
2    29000
3    31000
4    33000
5    35000
6    37000
7    39000
8    41000
9  1000000

In [23]:
# 5th and 95th percentile
lower = df1["Salary"].quantile(0.05)
upper = df1["Salary"].quantile(0.95)

print("Lower Limit:", lower)
print("Upper Limit:", upper)

Lower Limit: 25900.0
Upper Limit: 568449.999999999

In [24]:
outliers = df1[(df1["Salary"] < lower) | (df1["Salary"] > upper)]
print("Outliers:\n", outliers)

Outliers:
     Salary
0    25000
9  1000000

In [27]:
df1["Salary_capped"] = np.where(df1["Salary"] < lower, lower,
                       np.where(df1["Salary"] > upper, upper,
                                df1["Salary"]))

print(df1)

    Salary  Salary_capped
0    25000        25900.0
1    27000        27000.0
2    29000        29000.0
3    31000        31000.0
4    33000        33000.0
5    35000        35000.0
6    37000        37000.0
7    39000        39000.0
8    41000        41000.0
9  1000000       568450.0